AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'asev3-demo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'asev3-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: ${{ secrets.ACCOUNT_NAME }}
CICD_AGENT_TYPE: 'github'
